### PR TITLE
Added HyphenNameMapperNoDigits - it maps e.g. "implS3" to "impl-s3"

### PR DESCRIPTION
**Pull request by amorfis**
I use ficus and at work, we often have config classes like
```
case class MyConfig(impl: StorageImpl, local: Option[LocalStorageConfig], s3: Option[S3StorageConfig])
```
and we use hyphens in configs. So this maps to
```
impl = "S3"
s-3 = {
...
}
```

It would look much better if it was `s3` instead of `s-3`

This PR makes it possible

### CODE REVIEW

**Comment by amorfis** [comment]
Is anyone looking at this PRs? Or is the project dead? I need the change in ficus, but I don't want to fork another project of it if there is still one alive.

**Comment by kailuowang** [comment]
Can you just place the instance in your own project and use it? You don't
need it to live in ficus to be able to use it.

**Comment by amorfis** [comment]
@kailuowang I have many projects and I don't want to copy code. I can of course add this to some utils library and use in my projects. Or I can release my own version of `ficus`. I thought it might be useful also for others. However, I fully respect your opinion if it is different.

Thanks for the `ficus` library!

**Comment by kailuowang** [comment]
@amorfis thanks! 
Right now the PR still needs a scalafmt but I think once that's fixed I can merge and release. 

Going forward though, full transparency, I am not using ficus myself. Will you be interested in help maintaining this library?

**Comment by amorfis** [comment]
> @amorfis thanks!
> Right now the PR still needs a scalafmt but I think once that's fixed I can merge and release.
> 
> Going forward though, full transparency, I am not using ficus myself. Will you be interested in help maintaining this library?

Yes!

**Comment by amorfis** [comment]
Is it possible to check why scalafmt test doesn't pass? When I run `scalafmtCheckAll` on my machine there are no errors at all.

**Comment by kailuowang** [comment]
> Is it possible to check why scalafmt test doesn't pass? When I run `scalafmtCheckAll` on my machine there are no errors at all.

Cc @mdedetrich who set it up

**Comment by mdedetrich** [comment]
So I actually cloned https://github.com/amorfis/ficus/tree/hyphen-no-numbers and manually downloaded the scalafmt-native-musl release from https://github.com/scalameta/scalafmt/releases/tag/v2.7.5 and when I run scalafmt locally it passed without any problems.

I have no idea why the github action is failing since its also just downloading the same binary from the release and running it, there might be some weird git interaction I am not aware of? You can try dropping the `Formatting` commit and instead doing a rebase against https://github.com/iheartradio/ficus master, then running scalafmt + git commit ammend and then force pushing to see if it works.

Alternately @kailuowang can just merge this PR ignoring the failure.

**Comment by amorfis** [comment]
> Alternately @kailuowang can just merge this PR ignoring the failure.

But then the check is going to fail on master isn't it? And on all the future PRs.

**Comment by kailuowang** [comment]
I propose we replace native with sbt-scalafmt cmd on CI

**Comment by mdedetrich** [comment]
TBH I am not sure what this problem is because I have already integrated this precise solution in around 10 other Scala open source projects and this is the first time such a problem has happened.

Rationally speaking it leaves 2 possibilities

1. Simply put the contents of the git clone in the CI machine for w/e reason are different (this is why I suggested doing the rebase)
2. There is some weird error with this specific version of scalafmt

Something specifically being wrong with scalafmt-native looks highly unlikely. When I checked out @amorfis branch locally I also tried scalafmt via sbt cli and it reported the exact same result as scalafmt-native. In other words irrespective of what type of scalafmt I was using (native or sbt) I am unable to reproduce whats going on

I would prefer to diagnose this problem rather than ripping everything out. @amorfis if you are open to this, can you temporarily add

```scala
WorkflowStep.Sbt(List("scalafmtCheckAll"), name = Some("check format project"))
````

After this line https://github.com/iheartradio/ficus/blob/master/build.sbt#L11

Then make sure you run `sbt githubWorkflowGenerate`, this will update the https://github.com/iheartradio/ficus/blob/master/.github/workflows/ci.yml file.

Commit these changes (ideally as an ammend to your https://github.com/iheartradio/ficus/pull/140/commits/c3f020b073ba572e19f41ab5893e12dfcf0b4ee9 commit with a force push) and lets see what happens.

**Comment by amorfis** [comment]
Will do tomorrow as I gotta go already today 👍

**Comment by amorfis** [comment]
I rebased on master and looks like there are no errors now, but it also looks like actions did not run?

**Comment by kailuowang** [comment]
Closing and reopen to trigger GH action

**Comment by mdedetrich** [comment]
Awesome, it seems that scalafmt is working without problems now. Not sure what happened but it appears that rebase solve the issue.

**Comment by amorfis** [comment]
Osm! Thanks!

Do you plan to release new version anytime soon?

**Comment by mdedetrich** [comment]
If https://github.com/iheartradio/ficus/pull/166 can get merged before the release that would be great!

**Comment by amorfis** [comment]
I'd love to merge #139 too

**Pull request merged**
