### PR TITLE
support scala 2.13.0

### PR DESCRIPTION
**Pull request by codingismy11to7**

### CODE REVIEW

**Comment by fkowal** [comment]
Hey, to fix the failing tests please change the version sbt-scoverage in `project/plugins.sbt`

```
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.6.0")
```

**Comment by codingismy11to7** [comment]
will do, but...I did run tests before I pushed, on all versions, and nothing failed? are there other tests that I don't know about besides `sbt test`?

**Comment by kailuowang** [comment]
@codingismy11to7 the default `sbt test` runs on default scalaVersion which is 2.12, to run tests across all scala versions run `sbt +test`

**Comment by codingismy11to7** [comment]
I definitely ran `sbt +clean +test` before submitting, but just went and checked the `travis.yml` file to see what else i need to do. Still can't run `+coveralls` on my machine, but the xml file is now being written for all versions.

**Comment by codingismy11to7** [comment]
@kailuowang just pinging you that it passes now. I noticed @milessabin doesn't want to release macro-compat for 2.13, and he suggested to use "a similar mechanism to the one used by shapeless" without any links...so I don't know what that mechanism is...but I'm guessing it's just declaring the `bundle` class? Which is what I did.

**Comment by kailuowang** [comment]
thanks very much!

**Comment by kailuowang** [comment]
Released 1.4.6

**Comment by codingismy11to7** [comment]
awesome, thanks!

**Comment by milessabin** [comment]
@codingismy11to7 Yup, you did the right thing ... thanks. And apologies for being a bit vague.

**Pull request merged**
