### PR TITLE
Configure cross-compilation to Scala 2.12

### PR DESCRIPTION
**Pull request by jakubjanecek**
I have updated the build so that Ficus can be cross-compiled for Scala 2.12. Upgrade of some libraries was necessary and some compiler options had to be put under if.
I also had to update scoverage plugin. I know it's just release candidate version but I think this is fine for code coverage plugin.

I would appreciate if you could release it soon so that we can start using Scala 2.12. Thank you.

### CODE REVIEW

**Comment by kailuowang** [comment]
thanks a lot. Not sure I get the travis build error though, is there any other changes needed for the sbt coverage upgrade? (BTW, I don't mind the RC dependency)

**Comment by kailuowang** [comment]
Seems there is a problem with sbt-scoverage 1.4.0+ conflicting some existing sbt settings in ficus, causing a  configuration 'scoveragePlugin'  not found error. I couldn't find out the root cause here, and didn't figure out a solution either. I think I need some help here.

**Comment by jakubjanecek** [comment]
I don't have much experience with SBT nor with scoverage so I can't be of any help. Couldn't we just disable the code coverage plugin for now and enable it back once everything catches up with the new Scala version?

**Comment by kailuowang** [comment]
sbt-scoverage problem fixed in this merged PR https://github.com/iheartradio/ficus/pull/36. 
Do you mind merging in master as well as adding the new scala 2.12 version to travis? 
https://github.com/iheartradio/ficus/blob/master/.travis.yml#L6-L7

**Comment by jakubjanecek** [comment]
Thank you for your help. I tried it but it failed again. If I am not mistaken the problem is that scalac-scoverage-plugin is not compiled with the final Scala 2.12 release (https://github.com/scoverage/scalac-scoverage-plugin/blob/2bdb988315702d4eed5014d7f73f76a258513e8e/build.sbt) and the name of the artifact is scalac-scoverage-plugin_2.12.0-RC2 instead of scalac-scoverage-plugin_2.12.0.

They already have a pull request for final 2.12. Either way I think the code coverage could be disabled temporarily.

**Comment by kailuowang** [comment]
@jakubjanecek do you need this that urgently? It will be some work to disable it and reenable it. I do feel that they will release scoverage against 2.12.0 pretty soon.

**Comment by jakubjanecek** [comment]
I wouldn't want to wait weeks. So let's wait one week and we'll see...

**Comment by kailuowang** [comment]
@jakubjanecek you can track the progress here. https://github.com/scoverage/scalac-scoverage-plugin/issues/192

**Comment by kailuowang** [comment]
I believe this is ready. just need to update sbt-scoverage to 1.5.0

**Comment by jakubjanecek** [comment]
I did bump the version to `1.5.0` but I don't think it's released. `scalac-scoverage-plugin` was released (`1.3.0`) but `sbt-scoverage` is still not released :(

**Comment by kailuowang** [comment]
hmm, I got it from another project
> [info] downloading https://repo1.maven.org/maven2/org/scoverage/sbt-scoverage_2.10_0.13/1.5.0/sbt-scoverage-1.5.0.jar ...
[info] 	[SUCCESSFUL ] org.scoverage#sbt-scoverage;1.5.0!sbt-scoverage.jar (77ms)

**Comment by kailuowang** [comment]
Build passed. I am going to merge and release

**Comment by kailuowang** [comment]
Released at 1.3.2

**Comment by jakubjanecek** [comment]
Thank you!

**Comment by jakubjanecek** [comment]
Question, did you ask Bintray to publish the new Scala 2.12 artifact? Because even though I see the library in Bintray search I cannot download it from jcenter.bintray.com and I have similar problem with other libraries. Colleague told me that this might be the problem.

**Comment by kailuowang** [comment]
I am having trouble downloading the 2.11 artifacts as well. Same as you. I didn't have to do anything special in the past. Do you happen to know how I can ask Bintray?

**Comment by jakubjanecek** [comment]
Sorry, I don't know. My colleague is trying to find out with his open-source library so I will let you know if he finds out eventually.

**Comment by jakubjanecek** [comment]
Colleague told me that there was a button near right bottom corner of the Bintray page (detail of his library) which allowed him to ask for publishing on JCenter. I don't know if that's of any help...

**Comment by kailuowang** [comment]
@jakubjanecek it looks like that it's available on binray under iheartradio's repo so if you add
```
resolvers +=  Resolver.bintrayRepo("iheartradio","maven")
```
you should be able to get it.

**Comment by jakubjanecek** [comment]
I guess but that's not really systematic :( It's not just you, I know about other library with the same problem.

**Comment by jakubjanecek** [comment]
@kailuowang: My colleague was solving the same problem with his library and he had to contact support to change the configuration of "include path". This is the response from the support:
_Your previous included path was: com/avast/cactus_2.11 this caused your 2.12 package not to be part of (only) com/avast. We have modified your included path to be com/avast so you should be facing any conflicts._

Could you please contact the support of Bintray (via e-mail) and ask them to do the same for Ficus? Thank you.

**Pull request merged**
