### PR TITLE
Add EnumerationReader to support Scala's Enumeration type 

### PR DESCRIPTION
**Pull request by akkie**
Please see : https://github.com/ceedubs/ficus/pull/21

Is there something we could do to support Scala's Enumeration type ?

### CODE REVIEW

**Comment by akkie** [comment]
I've updated the code and also the readme. What do you think?

**Comment by kailuowang** [comment]
Thanks very much!

**Comment by kailuowang** [comment]
released 1.2.2 with this new feature.

**Comment by akkie** [comment]
:+1: Thanks!

**Pull request merged**
