### PR TITLE
Added readers for Java URI type

### PR DESCRIPTION
**Pull request by mdedetrich**
Note that the test I have added is pretty rudimentary. This is because generating random `java.net.URI` is non trivial (and I would have to add the functionality at first into scalacheck)

### CODE REVIEW

**Comment by kailuowang** [comment]
Thanks

**Comment by mdedetrich** [comment]
@kailuowang Awesome, would it be possible to let me know when a new version of ficus would be released? (i.e. is it possible to release one soon?)

**Comment by kailuowang** [comment]
I am on a vacation right now, I will release it next week when I go back in town

**Comment by mdedetrich** [comment]
Awesome, thanks!

**Comment by kailuowang** [comment]
released cc @shonzilla

**Pull request merged**
