### PR TITLE
Upgrade typesafe config

### PR DESCRIPTION
**Pull request by mdedetrich**
Bump to the newest related version of typesafe config

### CODE REVIEW

**Comment by kailuowang** [comment]
hmm, looks like we have some duplicated commits in this branch?

**Comment by mdedetrich** [comment]
@kailuowang I will do a rebase tonight

**Comment by mdedetrich** [comment]
@kailuowang The commits have been cleaned up

**Comment by kailuowang** [comment]
awesome. Thanks, I'll merge as soon as build green

**Pull request merged**
